version: '3'

services:

  nginx:
    image: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    networks: 
      - inception

  wordpress:
    image: wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

networks:
  inception:

volumes:
  mariadb_data: 
    driver: local
    driver_opts:
      type: none
      device: /home/alondot/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/alondot/data/wordpress
      o: bind