version: '3'

services:

  mariadb:
    image: mariadb:inception
    build:
      context: ./requirements/mariadb
    working_dir: /var/lib/mysql
    volumes:
      - vol_mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my_network

  nginx:
    image: nginx:inception
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - vol_wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - wordpress
    restart: always
  
  wordpress:
    image: wordpress:inception
    build:
      context: ./requirements/wordpress
    volumes:
      - vol_wordpress:/var/www/wordpress
    networks:
      - my_network
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

volumes:
  vol_wordpress:
    driver: local
    driver_opts:
      type: none
      device : /home/alondot/data/wordpress
      o: bind
  vol_mariadb:
    driver: local
    driver_opts:
      type: none
      device : /home/alondot/data/mysql
      o: bind
networks:
  my_network:
    driver: bridge
